version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: test-unit
    versions:
    - 3.3.9
    - 3.4.0
